#!/bin/sh

RED='\033[0;41;30m'
STD='\033[0;0;39m'

INSTALL_DIR="$HOME/.vim"

_install() {
    git clone git://github.com/adibis/.vim.git $INSTALL_DIR
    rm -rvf $HOME/.vimrc
    rm -rvf $HOME/.gvimrc
    ln -sv $INSTALL_DIR/config.vim $HOME/.vimrc
    ln -sv $INSTALL_DIR/gvim-config.vim $HOME/.gvimrc
    cd $INSTALL_DIR
    git submodule init
    git submodule update
}

_install_devel() {
    _install
    cd $INSTALL_DIR
    git checkout testing
}
_upgrade() {
    cd $INSTALL_DIR
    git pull origin master
}

_update() {
    cd $INSTALL_DIR
    git submodule foreach git pull origin master
}

# function to display menus
show_menus() {
	clear
	echo "~~~~~~~~~~~~~~~~~~~~~"
	echo "VIM Config Manager"
	echo "~~~~~~~~~~~~~~~~~~~~~"
	echo "1. Install Stable"
	echo "2. Install Development"
	echo "3. Update Repo"
	echo "4. Update Bundle"
    echo "5. Exit"
}

# read input from the keyboard and take a action
# Exit when user the user select 4 form the menu option.
read_options(){
	local choice
	read -p "Enter choice [ 1 - 5] " choice
	case $choice in
		1) _install ;;
        2) _install_devel ;;
		3) _upgrade ;;
		4) _update ;;
		5) exit 0;;
		*) echo -e "${RED}Error...${STD}" && sleep 2
	esac
}

# ----------------------------------------------
# Trap CTRL+C, CTRL+Z and quit singles
# ----------------------------------------------
trap '' SIGINT SIGQUIT SIGTSTP

# -----------------------------------
# Main logic - infinite loop
# ------------------------------------
while true
do
	show_menus
	read_options
done
